### ISSUE TITLE
Build launcher base

### ISSUE THREAD

**Issue by apachano** [GentenStudios/QuartzEngine#132]
Create a launcher that launches the game. The basics for an UI should be built so adding components is easier.

**Comment by apachano** [comment]
This is mostly complete, at this time I just need it to compile on Linux and we can mark it done and move to the next steps.

**Comment by tobyplowy** [comment]
@apachano @SuperFola Do I assign you guys?

**Comment by SuperFola** [comment]
Yep
~~Going to have a look at the code~~ No code yet, I was so tired I thought there was ^^'

**Comment by SuperFola** [comment]
Going to try making a small launcher with ImGUI, sending arguments to the (future) game

**Comment by apachano** [comment]
Updating this, per some slack discussions we are now using a separate language for the launcher. Currently, a rough prototype has begun at https://github.com/GentenStudios/PhoenixLauncher and we will move issues to that repo.
